id: 1
# start_url: https://m.hao123.com/
start_url: https://h5.mse.360.cn/newnavi.html#/home
max_steps: 10
timeout: 5000
reset_browser_timeout: 30000
num_envs: 32
headless: False
action:
  x_grain: 72
  y_grain: 128
policy_save_path: policy
ppo_n_steps: 96
log_path: /tmp/with-byol-full-traceback-2.log